#!/usr/bin/env python3
"""Generates FBWireMessages.pas from the Firebird message headers.

Usage: generate_messages.py <firebird-source-root> > FBWireMessages.pas

Reads src/include/firebird/impl/msg/{jrd,dsql,dyn,sqlerr,sqlwarn}.h -
the facilities a server round trip can produce - and emits a sorted
code table with the message format strings, consumed by
FindEngineMessage. The output is
committed; regenerating it is a maintenance task per Firebird release.
"""

import re
import subprocess
import sys

FACILITIES = {'JRD': 0, 'DSQL': 7, 'DYN': 8, 'SQLERR': 13, 'SQLWARN': 14}
ISC_BASE = 0x14000000

ENTRY = re.compile(
    r'^FB_IMPL_MSG(?:_NO_SYMBOL|_SYMBOL)?\(\s*(JRD|DSQL|DYN|SQLERR|SQLWARN)\s*,\s*(\d+)\s*,')

# the full form carries the sqlcode as its fourth argument
ENTRY_SQLCODE = re.compile(
    r'^FB_IMPL_MSG\(\s*(?:JRD|DSQL|DYN|SQLERR|SQLWARN)\s*,\s*\d+\s*,\s*\w+\s*,\s*(-?\d+)\s*,')

NO_SQLCODE = 32767  # sentinel: entry carries no sqlcode


def c_string_tail(line):
    """Extracts the final C string literal from an FB_IMPL_MSG line."""
    # walk back from the closing ')' to the string's opening quote,
    # honouring backslash escapes
    end = line.rstrip()
    if not end.endswith(')'):
        return None
    end = end[:-1].rstrip()
    if not end.endswith('"'):
        return None
    i = len(end) - 2
    while i >= 0:
        if end[i] == '"':
            # count preceding backslashes: an even number closes the string
            j = i - 1
            while j >= 0 and end[j] == '\\':
                j -= 1
            if (i - 1 - j) % 2 == 0:
                break
        i -= 1
    raw = end[i + 1:-1]
    # C escapes that occur in the message texts
    out = []
    k = 0
    while k < len(raw):
        c = raw[k]
        if c == '\\' and k + 1 < len(raw):
            n = raw[k + 1]
            if n == '"':
                out.append('"')
            elif n == '\\':
                out.append('\\')
            elif n == 'n':
                out.append('\n')
            elif n == 't':
                out.append('\t')
            else:
                out.append(n)
            k += 2
        else:
            out.append(c)
            k += 1
    return ''.join(out)


def pas_literal(text):
    """Renders text as a Pascal string literal (single line)."""
    parts = []
    lit = ''
    for ch in text:
        if ch == '\n':
            if lit:
                parts.append("'" + lit + "'")
                lit = ''
            parts.append('#10')
        elif ch == '\t':
            if lit:
                parts.append("'" + lit + "'")
                lit = ''
            parts.append('#9')
        else:
            lit += ch * 2 if ch == "'" else ch
    if lit or not parts:
        parts.append("'" + lit + "'")
    return '+'.join(parts)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    root = sys.argv[1]
    entries = {}
    counted = 0
    for name, fac in FACILITIES.items():
        path = f'{root}/src/include/firebird/impl/msg/{name.lower()}.h'
        for line in open(path, encoding='utf-8'):
            line = line.strip()
            m = ENTRY.match(line)
            if not m:
                continue
            counted += 1
            text = c_string_tail(line)
            if text is None:
                sys.exit(f'unparsable entry: {line}')
            code = ISC_BASE | (fac << 16) | int(m.group(2))
            msc = ENTRY_SQLCODE.match(line)
            sqlcode = int(msc.group(1)) if msc else NO_SQLCODE
            entries[code] = (text, sqlcode)

    try:
        commit = subprocess.check_output(
            ['git', '-C', root, 'rev-parse', '--short', 'HEAD'],
            text=True).strip()
    except Exception:
        commit = 'unknown'
    version = 'unknown'
    try:
        build_no = open(f'{root}/src/jrd/build_no.h', encoding='utf-8').read()
        major = re.search(r'FB_MAJOR_VER\s+"(\d+)"', build_no).group(1)
        minor = re.search(r'FB_MINOR_VER\s+"(\d+)"', build_no).group(1)
        version = f'{major}.{minor}'
    except Exception:
        pass

    codes = sorted(entries)
    w = sys.stdout.write
    w(f'''(*
 *  Firebird Interface (fbintf). The fbintf components provide a set of
 *  Pascal language bindings for the Firebird API.
 *
 *  This file is part of the pure Pascal wire protocol implementation
 *  and is subject to the Initial Developer's Public License Version 1.0.
 *
 *  The Initial Developer of the Original Code is MWA Software
 *  (http://www.mwasoftware.co.uk). All Rights Reserved.
 *
*)

{{GENERATED FILE - DO NOT EDIT.

 Engine error message texts for the facilities a server round trip can
 produce (JRD, DSQL, DYN, SQLERR, SQLWARN), so that the wire provider
 can format status
 vectors the way fb_interpret does without needing firebird.msg.

 Generated by generate_messages.py from the Firebird {version} message
 headers (src/include/firebird/impl/msg, commit {commit}).
 Regenerate per Firebird release.}}

unit FBWireMessages;

{{$IFDEF FPC}}
{{$mode delphi}}
{{$codepage UTF8}}
{{$ENDIF}}

interface

const
  {{an entry with no SQLCODE mapping}}
  NoSQLCode = 32767;

{{looks up the fb_interpret format string - with @1..@n parameter
 placeholders - for an engine error code. False when the code is not in
 the table (an unknown facility, or a newer server's message).}}
function FindEngineMessage(aCode: cardinal; var aFormat: AnsiString): boolean;

{{the SQLCODE the message database assigns to an engine error code, or
 NoSQLCode - what isc_sqlcode derives per status vector item}}
function EngineMessageSQLCode(aCode: cardinal): integer;

implementation

const
  MessageCount = {len(codes)};

  MessageCodes: array[0..MessageCount-1] of cardinal = (
''')
    for i in range(0, len(codes), 8):
        row = ', '.join(str(c) for c in codes[i:i + 8])
        sep = ',' if i + 8 < len(codes) else ');'
        w('    ' + row + sep + '\n')
    w('''
  MessageTexts: array[0..MessageCount-1] of AnsiString = (
''')
    for i, code in enumerate(codes):
        sep = ',' if i + 1 < len(codes) else ');'
        w('    {%d} %s%s\n' % (code, pas_literal(entries[code][0]), sep))
    w('''
  MessageSQLCodes: array[0..MessageCount-1] of smallint = (
''')
    for i in range(0, len(codes), 12):
        row = ', '.join(str(entries[c][1]) for c in codes[i:i + 12])
        sep = ',' if i + 12 < len(codes) else ');'
        w('    ' + row + sep + '\n')
    w('''
function FindMessageIndex(aCode: cardinal; var aIndex: integer): boolean;
var lo, hi, mid: integer;
begin
  Result := false;
  lo := 0;
  hi := MessageCount - 1;
  while lo <= hi do
  begin
    mid := (lo + hi) div 2;
    if MessageCodes[mid] = aCode then
    begin
      aIndex := mid;
      Exit(true);
    end;
    if MessageCodes[mid] < aCode then
      lo := mid + 1
    else
      hi := mid - 1;
  end;
end;

function FindEngineMessage(aCode: cardinal; var aFormat: AnsiString): boolean;
var idx: integer;
begin
  Result := FindMessageIndex(aCode,idx);
  if Result then
    aFormat := MessageTexts[idx];
end;

function EngineMessageSQLCode(aCode: cardinal): integer;
var idx: integer;
begin
  if FindMessageIndex(aCode,idx) then
    Result := MessageSQLCodes[idx]
  else
    Result := NoSQLCode;
end;

end.
''')
    print(f'{len(entries)} messages from {counted} entries',
          file=sys.stderr)


if __name__ == '__main__':
    main()
